### ISSUE TITLE
 feature request - constants randomization

### ISSUE THREAD

**Issue by sndcode** [XenocodeRCE/Noisette-Obfuscator#12]
for security wouldnt a "at least partially" randomized obfuscator break most of generic unpackers ? 
is the obfuscator unpackable atm by the way ?

**Comment by XenocodeRCE** [comment]
Hello,

what do you mean by "constants randomization" ? 

I'd be glad to code it.

**Comment by XenocodeRCE** [comment]
No reply, I close it.
