### ISSUE TITLE
What is Constant Melting?

### ISSUE THREAD

**Issue by marknefedov** [XenocodeRCE/Noisette-Obfuscator#15]
I don't quite understand what it is doing.

**Comment by XenocodeRCE** [comment]
- I commented partially the ![ConstantMeltingProtection.cs](https://github.com/XenocodeRCE/Noisette-Obfuscator/blob/master/Noisette/Protection/ConstantMelting/ConstantMeltingProtection.cs) file to give some hints
- It only put some instrruction's value on locals

```csharp
string markusgod = "test_123";
```
will become : 

```csharp
string gg54d6f54g;
string iuo646;
[...]
iuo646 = "test_123";
gg54d6f54g = iuo646;
string markusgod = gg54d6f54g;
```

**Comment by marknefedov** [comment]
Oh. thanks!
