### ISSUE TITLE
Missing dnlib

### ISSUE THREAD

**Issue by cyian-1756** [XenocodeRCE/Noisette-Obfuscator#2]
dnlib should be added to the repo as a submodule so when the repo is cloned dnlib is downloaded as well

**Comment by XenocodeRCE** [comment]
dnlib is actually inside the build/debug folder but YES i'll add it to the repo once I'm done with the constant mutation class. If you want you can do it yourself here is the correct branch https://github.com/yck1509/dnlib/tree/532c767a9a4f6af51cd4eb5d1c0af750c8509c5d

**Comment by XenocodeRCE** [comment]
@cyian-1756 As it is done now, I close this issue. Feel free to re-open it if necessary :)
