### ISSUE TITLE
[request] Make cross platform by removing use of Gdi32.dll

### ISSUE THREAD

**Issue by cyian-1756** [XenocodeRCE/Noisette-Obfuscator#3]
Using Gdi32.dll means that the program cannot be run under mono on *nix systems (Linux, OSX ect) as you are directly invoking a Windows DLL.

**Comment by XenocodeRCE** [comment]
Maybe I'll solve it in the same time I'll do a CommandLineArgument system, and I plan to remove the GUI. GUI was just to attract peopl in fact.

**Comment by XenocodeRCE** [comment]
Done via the CLI program
