### ISSUE TITLE
Output not working

### ISSUE THREAD

**Issue by ghost** [XenocodeRCE/Noisette-Obfuscator#6]
the title explains everything... here is a link of the file im obfuscating.

http://www67.zippyshare.com/v/eWFAF11j/file.html

**Comment by XenocodeRCE** [comment]
Nice, now happy debugging, update the issue one you find the cause :)

**Comment by ghost** [comment]
startup form has not been specified are u kidding me? VS got cancer or sth?

**Comment by XenocodeRCE** [comment]
No reply since 25 days, I close this.
